basePath: /
host: localhost:8080
info:
  contact: {}
  title: Bill App API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
